### PR TITLE
Ifdef va_x11 in VP sample for usrptr

### PR DESCRIPTION
**Pull request by edwarddavidbaker**
When updating libva-utils from 2.4.0 to 2.6.0 in Chrome OS I bumped into
the following error:
```
portage/media-video/libva-utils-2.6.0-r1/work/libva-utils-2.6.0/videoprocess/vppscaling_n_out_usrptr.cpp:41:10: fatal error:
      'va/va_x11.h' file not found
```

Signed-off-by: Edward Baker <edward.baker@intel.com>

### CODE REVIEW

**Comment by edwarddavidbaker** [comment]
Thanks for merging. I thought the same thing about removing directly, but decided to maintain consistency in vppscaling_n_out_usrptr.cpp. The rest of the file used an #if 0 approach for X11 pieces.
https://github.com/intel/libva-utils/blob/master/videoprocess/vppscaling_n_out_usrptr.cpp#L73
https://github.com/intel/libva-utils/blob/master/videoprocess/vppscaling_n_out_usrptr.cpp#L781
